/** Direct listing getters + DirectListed — for receipt screen only. */
export const directListingAbi = [
  {
    type: 'event',
    name: 'DirectListed',
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'startMcap', type: 'uint256', indexed: false },
      { name: 'listed', type: 'uint256', indexed: false },
      { name: 'sidePoolTokens', type: 'uint256', indexed: false },
      { name: 'creatorReserve', type: 'uint256', indexed: false },
      { name: 'instant', type: 'bool', indexed: false },
      { name: 'createSidePool', type: 'bool', indexed: false },
      { name: 'sidePoolBps', type: 'uint16', indexed: false },
      { name: 'liquidityLocked', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'token',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'creator',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'startMcap',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'startPriceWad',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'startTick',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'int24' }],
  },
  {
    type: 'function',
    name: 'creatorReserve',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createSidePool',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'sidePoolBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'liquidityLocked',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'sidePoolDeployed',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'ethUsdWad',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'creatorReserveState',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'mode', type: 'uint8' },
      { name: 'vestDuration', type: 'uint64' },
      { name: 'unlockedAt', type: 'uint64' },
      { name: 'total', type: 'uint256' },
      { name: 'claimed', type: 'uint256' },
      { name: 'filed', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'mainKey',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'currency0', type: 'address' },
          { name: 'currency1', type: 'address' },
          { name: 'fee', type: 'uint24' },
          { name: 'tickSpacing', type: 'int24' },
          { name: 'hooks', type: 'address' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'sideKey',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'currency0', type: 'address' },
          { name: 'currency1', type: 'address' },
          { name: 'fee', type: 'uint24' },
          { name: 'tickSpacing', type: 'int24' },
          { name: 'hooks', type: 'address' },
        ],
      },
    ],
  },
] as const
