/**
 * Ladder factory ABI — GENERATED by scripts/gen-ladder-abi.mjs. Do not hand-edit.
 *
 * `AuctionFiled` is the discovery event: index it the way scanner.ts indexes `ExpressListed`.
 *
 * Filing is gated by DeployControls (`_requireDeployAllowed`), so `file` is reachable only by an
 * allowlisted deployer: any form built on it MUST read `deploysEnabled` / `allowlistCount` /
 * `isDeployerAllowed` first and say plainly that a non-allowlisted wallet would revert
 * `DeployerNotAllowed` (see ladder/LadderFileForm.tsx). The production overload is
 * `file(params, userSalt)`, which additionally requires the predicted auction address to carry the 0x4663
 * vanity prefix (16 bits, so cheap to mine client-side, unlike the hook's 30).
 */

export const ladderFactoryAbi = [
    {
      "type": "function",
      "name": "DEFAULT_SIDE_POOL_BPS",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_ETH_DEFAULT",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_ETH_MAX",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_ETH_MIN",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_USDG_DEFAULT",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_USDG_MAX",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REF_PRICE_USDG_MIN",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "SIDE_POOL_BPS_MAX",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "allowlistCount",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "assertSoftLaunchGate",
      "inputs": [
        {
          "name": "expectedDeployer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "auctionCreationPtr0",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "auctionCreationPtr1",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "auctionInitCodeHash",
      "inputs": [
        {
          "name": "p",
          "type": "tuple",
          "internalType": "struct StonkzLadderAuction.Params",
          "components": [
            {
              "name": "supply",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "name",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "symbol",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "floorMcap",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "duration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpShareWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpHealthTargetWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "carveBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "cashHoldbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackDelivery",
              "type": "uint8",
              "internalType": "enum LadderConstants.HoldbackDelivery"
            },
            {
              "name": "tier",
              "type": "uint8",
              "internalType": "enum LadderTypes.Tier"
            },
            {
              "name": "createSidePool",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "sidePoolBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "refPriceWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "walletCapBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "sizeBonusBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "maxUniqueActives",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "pairToken",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "creator",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "treasury",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "vaultRef",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "settlement",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "ethUsdWad",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "auctionSalt",
      "inputs": [
        {
          "name": "deployer",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "userSalt",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "carveTreasury",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "currentEthUsdWad",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "defaultCarveBps",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "defaultCreateSidePool",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "defaultLiquidityLocked",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "defaultSidePoolBps",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "deploysEnabled",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "ethUsdStampBandBps",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "feeLockerRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "file",
      "inputs": [
        {
          "name": "p",
          "type": "tuple",
          "internalType": "struct StonkzLadderAuction.Params",
          "components": [
            {
              "name": "supply",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "name",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "symbol",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "floorMcap",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "duration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpShareWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpHealthTargetWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "carveBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "cashHoldbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackDelivery",
              "type": "uint8",
              "internalType": "enum LadderConstants.HoldbackDelivery"
            },
            {
              "name": "tier",
              "type": "uint8",
              "internalType": "enum LadderTypes.Tier"
            },
            {
              "name": "createSidePool",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "sidePoolBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "refPriceWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "walletCapBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "sizeBonusBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "maxUniqueActives",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "pairToken",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "creator",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "treasury",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "vaultRef",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "settlement",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "ethUsdWad",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "auction",
          "type": "address",
          "internalType": "contract StonkzLadderAuction"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "file",
      "inputs": [
        {
          "name": "p",
          "type": "tuple",
          "internalType": "struct StonkzLadderAuction.Params",
          "components": [
            {
              "name": "supply",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "name",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "symbol",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "floorMcap",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "duration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpShareWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "lpHealthTargetWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "carveBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "cashHoldbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "holdbackDelivery",
              "type": "uint8",
              "internalType": "enum LadderConstants.HoldbackDelivery"
            },
            {
              "name": "tier",
              "type": "uint8",
              "internalType": "enum LadderTypes.Tier"
            },
            {
              "name": "createSidePool",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "sidePoolBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "refPriceWad",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "walletCapBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "sizeBonusBps",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "maxUniqueActives",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "pairToken",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "creator",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "treasury",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "vaultRef",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "settlement",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "ethUsdWad",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        },
        {
          "name": "userSalt",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "auction",
          "type": "address",
          "internalType": "contract StonkzLadderAuction"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "isDeployerAllowed",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "poolManagerRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract IPoolManager"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "predictAuctionAddress",
      "inputs": [
        {
          "name": "deployer",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "userSalt",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "initCodeHash",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "predicted",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refAgreementBps",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refCheckEthIs0",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refCheckStableDecimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPoolCheck",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPoolManager",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPoolPrimary",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPriceConfigured",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPriceWad",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPrimaryEthIs0",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "refPrimaryStableDecimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "requireEthUsdFresh",
      "inputs": [
        {
          "name": "suppliedWad",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "settlementRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "sideTokenRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "vaultRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "weightsRef",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract LadderWeightsStore"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "AuctionFiled",
      "inputs": [
        {
          "name": "auction",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "creator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "holdbackBps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        },
        {
          "name": "carveBps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        },
        {
          "name": "userSalt",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "salt",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CarveTreasuryChanged",
      "inputs": [
        {
          "name": "carveTreasury",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DefaultCarveBpsSet",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DefaultCreateSidePoolSet",
      "inputs": [
        {
          "name": "createSidePool",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DefaultLiquidityLockedSet",
      "inputs": [
        {
          "name": "locked",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DefaultSidePoolBpsSet",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DeployerAllowed",
      "inputs": [
        {
          "name": "deployer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DeployerRevoked",
      "inputs": [
        {
          "name": "deployer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "DeploysEnabled",
      "inputs": [
        {
          "name": "enabled",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "EthUsdStampBandBpsSet",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "FeeLockerRefSet",
      "inputs": [
        {
          "name": "feeLocker",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "OwnerTransferred",
      "inputs": [
        {
          "name": "prev",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "next",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "PoolManagerRefSet",
      "inputs": [
        {
          "name": "poolManager",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RefAgreementBpsSet",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RefPoolsSet",
      "inputs": [
        {
          "name": "poolManager",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "primaryId",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "primaryEthIs0",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        },
        {
          "name": "primaryStableDec",
          "type": "uint8",
          "indexed": false,
          "internalType": "uint8"
        },
        {
          "name": "checkId",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "checkEthIs0",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        },
        {
          "name": "checkStableDec",
          "type": "uint8",
          "indexed": false,
          "internalType": "uint8"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RefPriceChanged",
      "inputs": [
        {
          "name": "sideToken",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "pairCurrency",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "refPriceWad_",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SettlementCloned",
      "inputs": [
        {
          "name": "auction",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "clone",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "impl",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SettlementRefSet",
      "inputs": [
        {
          "name": "settlement",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SideTokenRefSet",
      "inputs": [
        {
          "name": "sideToken",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "VaultRefSet",
      "inputs": [
        {
          "name": "vault",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WeightsRefSet",
      "inputs": [
        {
          "name": "weights",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AlreadyAllowed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AuctionCreateFailed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CarveBounds",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CarveTreasuryUnset",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CarveTreasuryZero",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CreationCodePointerMissing",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CreationCodeTooLarge",
      "inputs": []
    },
    {
      "type": "error",
      "name": "DeployerNotAllowed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "DeploysOff",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EmptyCreationCode",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EthUsdStampBandBpsOutOfBounds",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "EthUsdStampDrift",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "current",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "FeeLockerRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "HoldbackCeiling",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotOnAllowlist",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotOwner",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PoolManagerRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "RefAgreementBpsOutOfBounds",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "RefPoolEmpty",
      "inputs": [
        {
          "name": "poolId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "RefPoolUnset",
      "inputs": []
    },
    {
      "type": "error",
      "name": "RefPoolsDisagree",
      "inputs": [
        {
          "name": "primaryWad",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "checkWad",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "RefPriceOutOfBounds",
      "inputs": [
        {
          "name": "pairCurrency",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "price",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "RefPriceUnset",
      "inputs": [
        {
          "name": "sideToken",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "pairCurrency",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "SettlementRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SidePoolBpsOutOfBounds",
      "inputs": [
        {
          "name": "bps",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "SideTokenRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SideTokenRefUnset",
      "inputs": []
    },
    {
      "type": "error",
      "name": "VanityPrefixMismatch",
      "inputs": [
        {
          "name": "predicted",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "VaultRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "VaultRequiredForHoldback",
      "inputs": []
    },
    {
      "type": "error",
      "name": "WeightsRefNotContract",
      "inputs": []
    },
    {
      "type": "error",
      "name": "WeightsRefUnset",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ZeroAddress",
      "inputs": []
    }
  ] as const

/** topic0 of `AuctionFiled(address,address,uint16,uint16,bytes32,bytes32)` — anchor so a scanner refuses to run against a drifted ABI. */
export const LADDER_AUCTION_FILED_TOPIC0: `0x${string}` =
  '0x481cc0c717c31f71dbe294306a9ece6d39c873ee572d83179c8a67cc532fe168'
